= 08 - Cross-cutting Concepts
:description: This section describes overall, principal regulations and solution ideas that are relevant in multiple parts (= cross-cutting) of your system.

== Manage Github Config and Repositories with Terraform
To maintain a centralized and consistent approach to managing GitHub repositories and configurations, we useuse Terraform as a tool for provisioning and managing these resources. 

All repositories and projects are part of the link:https://github.com/sommerfeld-io[sommerfeld-io organization].

link:https://www.terraform.io[Terraform] is an infrastructure-as-code (IaC) tool that allows you to define and manage infrastructure resources across various cloud providers and services.

By leveraging Terraform to handle all GitHub repositories and global GitHub configurations, we aim to establish a single source of truth for all GitHub-related resources. This approach ensures that all repositories and configurations are defined in a declarative manner using Terraform's configuration language, which allows for version control, collaboration, and reproducibility.

[plantuml, puml-build-image, svg]
----
@startuml

skinparam linetype ortho
skinparam monochrome false
skinparam componentStyle uml2
skinparam backgroundColor #fff
skinparam ArrowColor black
skinparam NoteBorderColor Grey
skinparam NoteBackgroundColor #fdfdfd
skinparam defaultTextAlignment center
skinparam activity {
FontName Ubuntu
}

actor me as "sebastian-sommerfeld-io"
entity GH_TOKEN_REPO_AND_PROJECT <<Fine Grained Access Token>>
me -> GH_TOKEN_REPO_AND_PROJECT
note right of me: Create manually
note left of GH_TOKEN_REPO_AND_PROJECT: Store manually\nin Bitwarden

component vault as "Bitwarden\nVault"
GH_TOKEN_REPO_AND_PROJECT -> vault

component dev_repo as "dev-environment-config" <<Repo>> {
    file tf as "Terraform\nConfig"
    note right of tf: Write Github Actions secrets\nto Organization and Repos
    
    entity TERRAFORM <<Actions Secret + Classic Access Token>>
    
    entity BW_CLIENT_ID <<Actions Secret>>
    entity BW_CLIENT_SECRET <<Actions Secret>>
    entity BW_MASTER_PASS <<Actions Secret>>
}
vault -down-> tf

component org as "Github\nOrganization"
database r1 as "Repo\n1"
database r2 as "Repo\n..."
database r3 as "Repo\nn"

tf -> org
tf -> r1
tf -> r2
tf -> r3

@enduml
----

. Token `GH_TOKEN_REPO_AND_PROJECT` (valid for 90 days)
.. Configured for user `sebastian-sommerfeld-io`
.. Read access to metadata
.. Read and Write access to code, secrets, and workflows 
. Token `TERRAFORM` Personal Access Token (classic)
.. Configured for user `sebastian-sommerfeld-io`
.. `admin:org`, `read:user`, `repo`, `workflow`

By adopting this approach, we can achieve a unified and streamlined process for managing GitHub repositories and configurations. Terraform provides the necessary tools and capabilities to establish a single source of truth, improving efficiency, governance, and collaboration within the organization's development workflow.
