= Development Guidelines
Sebastian Sommerfeld <sebastian@sommerfeld.io>

Our approach and guidelines to software development. These principles apply to every project we are developing.

== Version Control
We make all changes to code, test, infrastructure, configuration, and ultimately production via version control.

Version control extends beyond just managing code repositories like Git. It encompasses a broader scope that includes controlling the versions of tools and third-party software utilized within our environments. By actively managing these dependencies, we ensure that our software remains stable, consistent, and immune to uncontrolled changes originating from external sources.

We employ version control to manage and track changes made to our production systems, ensuring that modifications are controlled, traceable, and reversible.

By extending version control to encompass the management of tools, third-party software and production environment, we maintain a firm grip on the external factors that can impact our software development and our runtime environments. This approach allows us to minimize the risk of uncontrolled changes.

== Continuous Integration
We integrate code changes from all developers at least once per day. This frequent integration ensures that our software is thoroughly tested and checked with everyone's changes on a daily basis.

We work with short lived (feature) branches. But we won't hide work on separate branches for longer than a working day before integrating them together.

We don't merge the main branch into our feature branches to make them live longer! This is not a way to integrate everyone's changes into a single source of truth and prevents us from determining the releasability of our software. 

We grow our code incrementally, making frequent small changes to our code - leaving our code in a working state after each small change.

We get feedback on the quality of our work after every small change through the use of automated tests in pipelines.

== Automated tests determine the releasability
We automate almost everything in our pipeline(s), and have enough automated testing to in place to validate and release our changes without dependence on manual regression testing, or approval QA and approval processes.

Manual tests are not forbidden. But since the only make us feel better and more save instead of providing a real judgement on the releasability of our software, the make it or break it desicion always comes from our pipeline(s).

When we identify manual tests that are performed repeatedly, we actively work on transforming them into automated tests and integrate them into our pipelines.

== Keep the software always in a releasable state
While we may not release our software daily, our goal is to have the capability to release changes every day if required. To achieve this goal we have to keep our software in a releaseable state all the time! 

== Releases and Deployments always are done through a pipeline
We can deploy our changes into production, or any test environment, "at the touch of a button".

This means that all deployments to any test environment, whether it's a software version to some test environment or to production or a Docker image to DockerHub or any other kind of deployment, are carried out automatically via dedicated pipelines. 

This pipeline (and all predesessing pipelines) include all steps and tests that are sufficient to determine the releasability of our software. When a change has completed its transit through the pipeline(s), there is no more work to do for the software to be released into production other than triggering the release itself. This is done through a dedicated "Release + Deploy" Pipeline. Deployments are never done manually! This pipeline also documents this as a release.

[plantuml, puml-build-image, svg]
----
@startuml

'skinparam linetype ortho
skinparam monochrome false
skinparam componentStyle uml2
skinparam backgroundColor #0D1117
skinparam ArrowColor #e6edf3
skinparam NoteBorderColor #e6edf3
skinparam NoteFontColor #e6edf3
skinparam NoteBackgroundColor transparent
skinparam ComponentBorderColor #e6edf3
skinparam ComponentFontColor #e6edf3
skinparam DatabaseBorderColor #e6edf3
skinparam DatabaseBackgroundColor #444
skinparam DatabaseFontColor #e6edf3
skinparam FileBorderColor #e6edf3
skinparam FileFontColor #e6edf3
skinparam ControlBorderColor #e6edf3
skinparam ControlFontColor #e6edf3
skinparam RectangleBackgroundColor transparent
skinparam RectangleBorderColor #e6edf3
skinparam RectangleFontColor #e6edf3
skinparam ControlBackgroundColor transparent
skinparam ControlBorderColor #e6edf3
skinparam ControlFontColor #e6edf3
skinparam HexagonBackgroundColor transparent
skinparam HexagonBorderColor #e6edf3
skinparam HexagonFontColor #e6edf3
skinparam ArtifactBackgroundColor #444
skinparam ArtifactBorderColor #e6edf3
skinparam ArtifactFontColor #e6edf3
skinparam defaultTextAlignment center
skinparam activity {
FontName Ubuntu
}

file code as "Source\nCode" #E18114
database code_repo as "Code\nRepo" #E18114
database artifact_repo as "Artifact\nRepo"
control ci as "Automated Tests\nSoftware Builds\nCode Scans\netc." #E18114

code -> code_repo
code_repo -right-> ci
ci -down-> artifact_repo

control more as "More\nTests" #35A339
control acceptance as "Acceptance\nTests" #35A339
control security as "Security\nTests" #35A339
control performance as "Performance\nTests" #35A339
artifact_repo -right-> acceptance
artifact_repo -down-> security
artifact_repo -down-> performance
artifact_repo -down-> more

control deploy as "Release + Deploy\nPipeline" #2F81F7
component prod as "Production\nEnvironment" #2F81F7

artifact_repo -left-> deploy
deploy -left-> prod

code_repo -[hidden]right- artifact_repo

@enduml
----

* _Yellow = Commit Phase -> Is the software tecnically correct?_
* _Green = Acceptance Phase -> Is the software releaseable?_
* _Blue = Production Phase -> The software is published and in use_

Artifacts are versioned using semantic versioning (e.g. `v0.1.0`). Unstable versions are marked as a Snapshot (e.g. `v0.1.0-SNAPSHOT`) before beeing released as stable.

== Artifacts are immutable
We are validating the delivered artifact with the pipeline. It is built once and deployed to all environments. A common anti-pattern is building an artifact for each environment. 

== User Stories
We want requirements to define small focused needs rather than vast vague projects. We use user stories to describe our requirements. We try to finish a user story within a couple of days at most. We need to keep in mind, that we integrate our changes daily, so we must design our user stories accordingly.

If we can't think of user need in terms of a story, we don't understand what our software is meant to achieve yet. If we can't think of an example, that would demonstrate that the need is fullfilled, we don't really understand the problem (domain) yet.
