= Github Organization Settings
Sebastian Sommerfeld <sebastian@sommerfeld.io>

This page lists all configurations for the link:https://github.com/sommerfeld-io[sommerfeld-io Github organization] wich are done manually.

== Configuring the default `GITHUB_TOKEN` permissions
By default, when you create a new repository in your personal account, `GITHUB_TOKEN` only has read access for the `contents` and `packages` scopes. If you create a new repository in an organization, the setting is inherited from what is configured in the organization settings.

. On GitHub.com, navigate to the main page of the repository.
. Under your repository name, click *Settings*. If you cannot see the "Settings" tab, select the dropdown menu, then click *Settings*.
. In the left sidebar, click *Actions*, then click *General*.
. Under "Workflow permissions", choose whether you want the `GITHUB_TOKEN` to have read and write access for all scopes, or just read access for the `contents` and `packages` scopes.
.. For the sommerfeld-io ogranization choose *Read repository contents and packages permissions*.
.. For the sommerfeld-io ogranization check *Allow Github Actions to create and approve pull requests*.
. Click Save to apply the settings.

NOTE: See link:https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions[Configuring the default `GITHUB_TOKEN` permissions] on the Github docs pages for more information.

